theme: "hugo-theme-novela"
baseURL: "https://cervecera.netlify.app"
languageCode: "en-us"
title: "Cervecera Heineken Meoqu√≠"
pygmentsstyle: 'monokai'
paginate: 6

  [menu]
      [[menu.main]]
          identifier = "about"
          Name = "About"
          url = "/about/"
          weight = 0

social:
  twitter: "https://twitter.com/JLManzanaresR"
  youtube: "https://www.youtube.com/watch?v=uJMiS4pNzQ4"
taxonomies:
  author: authors
  math: true
